# - Find LimaLP

if ("x${LIB_INSTALL_DIR}" STREQUAL "x")
  set(LIB_INSTALL_DIR "lib")
endif ()

set(LIMALP_INCLUDE_DIR @CMAKE_INSTALL_PREFIX@/include)
set(LIMALP_LIBRARY_DIRS @CMAKE_INSTALL_PREFIX@/${LIB_INSTALL_DIR} )

message(STATUS "Lima version  ${LIMA_VERSION_MAJOR}.${LIMA_VERSION_MINOR}.${LIMA_VERSION_RELEASE} - LIMA_GENERIC_LIB_VERSION  ${LIMA_GENERIC_LIB_VERSION} ")
