# - Find LimaLP

SET(LIMALP_INCLUDE_DIR @CMAKE_INSTALL_PREFIX@/include)
SET(LIMALP_LIBRARY_DIRS @CMAKE_INSTALL_PREFIX@/lib )

message(STATUS "Lima version  ${LIMA_VERSION_MAJOR}.${LIMA_VERSION_MINOR}.${LIMA_VERSION_RELEASE} - LIMA_GENERIC_LIB_VERSION  ${LIMA_GENERIC_LIB_VERSION} ")
