set VERBOSE=1

set QTDIR=C:\Qt\5.14.2\msvc2017_64
set WINKITDIR="C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64"
set MSYSDIR=c:\msys64\usr\bin
set NINJADIR=C:\Externe
set BOOST_ROOT=C:\local\boost_1_74_0\lib64-msvc-14.1\cmake
set NLTK_PTB_DP_DIR=%HOMEDRIVE%\%HOMEPATH%\Application^ Data\nltk_data\corpora\dependency_treebank
set LIMA_SRC=c:\projects\lima
set CXX=cl
set Eigen3_DIR="C:\Program Files (x86)\Eigen3"

set BLD_DIR=c:\\b
set LIMA_DIST=c:\\d

cd %BLD_DIR%

set BOOST_LIBRARYDIR=C:\local\boost_1_74_0\lib64-msvc-14.1
set BOOST_INCLUDEDIR=C:\local\boost_1_74_0\
set ICU_INCLUDEDIR=C:\Externe\icu4c\include
set Eigen3_INCLUDEDIR=C:\Program Files (x86)\Eigen3
set LIMA_EXTERNALS=%LIMA_DIST%
set LIMA_CONF=%BLD_DIR%\execEnv\config
set LIMA_RESOURCES=%BLD_DIR%\execEnv\resources
set PATH=%BLD_DIR%\execEnv\lib;%NINJADIR%;%Eigen3_INCLUDEDIR%;%ICU_INCLUDEDIR%;%TFDIR%;%QTDIR%\bin;%BOOST_LIBRARYDIR%;%MSYSDIR%;%WINKITDIR%;%PATH%
set LIMA_DISABLE_FSW_TESTING=true
set NLTK_PTB_DP_FILE=%NLTK_PTB_DP_DIR%\nltk-ptb.dp
set LIBTORCH_PATH=%LIMA_SRC%/extern/libtorch/
set LIMA_VERSION_RELEASE=20181218114529-d9467701

cmake -G "Ninja" "-DCMAKE_PREFIX_PATH=%QTDIR%;%BOOST_ROOT%;%BOOST_INCLUDEDIR%;%EIGEN3_INCLUDEDIR%;%ICU_INCLUDEDIR%;%LIBTORCH_PATH%" -DBOOST_ROOT=%BOOST_ROOT% -DBOOST_LIBRARYDIR:STRING=%BOOST_LIBRARYDIR% "-DLIMA_RESOURCES=build" "-DLIMA_VERSION_RELEASE:STRING=%LIMA_VERSION_RELEASE%" "-DTF_SOURCES_PATH=%TFINCLUDE%" -DCMAKE_BUILD_TYPE=RelWithDebInfo "-DCMAKE_INSTALL_PREFIX=%LIMA_DIST%" -DEigen3_DIR=%Eigen3_DIR% -DCMAKE_IGNORE_PATH=%MSYSDIR% %LIMA_SRC% -DWITH_DEBUG_MESSAGES=ON -DWITH_ARCH=OFF -DWITH_ASAN=OFF -DSHORTEN_POR_CORPUS_FOR_SVMLEARN=ON -DWITH_GUI=ON
cmake --build . --config RelWithDebInfo -- -v -j 6

cd %LIMA_SRC%