FROM ubuntu:14.04

ENV LANG en_US.UTF-8

ARG BINTRAYKEY
ARG TRAVIS_JOB_NUMBER 
ARG NLTK_PTB_DP_FILE
ARG LIMA_DIST
ARG LIMA_CONF
ARG LIMA_RESOURCES
ARG PATH
ARG LD_LIBRARY_PATH
ARG LIMA_DISABLE_FSW_TESTING
ARG LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS
ARG release

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y apt-utils -qq
RUN apt-get install -y git gcc g++ autotools-dev dh-autoreconf cmake cmake-data curl python-nltk gawk wget -qq
RUN apt-get install -y qt5-default qtbase5-dev-tools libqt5xmlpatterns5-dev libqt5qml5 qtdeclarative5-dev libboost-all-dev libenchant-dev -qq

RUN curl -sL https://deb.nodesource.com/setup | bash -
RUN apt-get install -y nodejs 
RUN npm install -g json


RUN sed -ie "s|DEFAULT_URL = 'http://nltk.googlecode.com/svn/trunk/nltk_data/index.xml'|DEFAULT_URL = 'http://nltk.github.com/nltk_data/'|" /usr/lib/python2.7/*/nltk/downloader.py
RUN python -m nltk.downloader -d nltk_data dependency_treebank
RUN cat nltk_data/corpora/dependency_treebank/wsj_*.dp | grep -v "^$" > nltk_data/corpora/dependency_treebank/nltk-ptb.dp

RUN wget https://bintray.com/artifact/download/kleag/ubuntu-14.04/$(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/qhttpserver/versions/$(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/qhttpserver | json -a latest_version)/files | json 0.path)
RUN dpkg -i $(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/qhttpserver/versions/$(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/qhttpserver | json -a latest_version)/files | json 0.name)
RUN wget https://bintray.com/artifact/download/kleag/ubuntu-14.04/$(echo $(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/svmtool-cpp/versions/$(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/svmtool-cpp | json -a latest_version)/files | json 0.path)  | sed -e 's/\+/%2B/g')
RUN dpkg -i $(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/svmtool-cpp/versions/$(curl https://api.bintray.com/packages/kleag/ubuntu-14.04/svmtool-cpp | json -a latest_version)/files | json 0.name)

RUN mkdir -p /src/
RUN git clone https://github.com/aymara/lima /src/lima
WORKDIR /src/lima
RUN git pull


RUN mkdir -p /src/lima/build
 
# Build
WORKDIR /src/lima/build
RUN cmake -DLIMA_RESOURCES:STRING=build -DCMAKE_INSTALL_PREFIX:PATH=$LIMA_DIST -DCMAKE_BUILD_TYPE:STRING=Release  -DLIMA_VERSION_RELEASE:STRING="$release" ..
RUN make -j4

WORKDIR $LIMA_DIST/share/apps/lima/tests
RUN tva --language=eng test-eng.*.xml 2>&1 | tee tva-eng.log
RUN tva --language=fre test-fre.default.xml test-fre.disambiguated.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.sa.xml test-fre.se.xml test-fre.simpleword.xml test-fre.tokenizer.xml 2>&1 | tee tva-fre.log

RUN curl -ukleag:$BINTRAYKEY -T /home/travis/build/aymara/lima/build/lima_common-prefix/src/lima_common-build/limacommon-2.1.$release-runtime.deb  https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limacommon-2.1.$release-runtime.deb
RUN curl -ukleag:$BINTRAYKEY -T /home/travis/build/aymara/lima/build/lima_common-prefix/src/lima_common-build/limacommon-2.1.$release-devel.deb  https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limacommon-2.1.$release-devel.deb
RUN curl -ukleag:$BINTRAYKEY -T /home/travis/build/aymara/lima/build/lima_linguisticprocessing-prefix/src/lima_linguisticprocessing-build/limalinguisticprocessing-2.1.$release-runtime.deb https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticprocessing-2.1.$release-runtime.deb
RUN curl -ukleag:$BINTRAYKEY -T /home/travis/build/aymara/lima/build/lima_linguisticprocessing-prefix/src/lima_linguisticprocessing-build/limalinguisticprocessing-2.1.$release-devel.deb https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticprocessing-2.1.$release-devel.deb
RUN curl  -ukleag:$BINTRAYKEY -T/home/travis/build/aymara/lima/build/lima_linguisticdata-prefix/src/lima_linguisticdata-build/limalinguisticdata-2.1.$release-common.deb  https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticdata-2.1.$release-common.deb
RUN curl  -ukleag:$BINTRAYKEY -T/home/travis/build/aymara/lima/build/lima_linguisticdata-prefix/src/lima_linguisticdata-build/limalinguisticdata-2.1.$release-eng.deb  https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticdata-2.1.$release-eng.deb
RUN curl  -ukleag:$BINTRAYKEY -T/home/travis/build/aymara/lima/build/lima_linguisticdata-prefix/src/lima_linguisticdata-build/limalinguisticdata-2.1.$release-fre.deb  https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/limalinguisticdata-2.1.$release-fre.deb
RUN curl -XPOST -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER/publish
RUN curl -XGET https://bintray.com/kleag/ubuntu-14.04/lima/$TRAVIS_JOB_NUMBER


