# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#

version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "15.3.0"

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            brew update
            brew install qt@6 boost cmake ninja
      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake  -G Ninja \
                -DQT_VERSION_MAJOR=6 \
                -DWITH_DEBUG_MESSAGES=OFF \
                -DWITH_ARCH=OFF \
                -DWITH_ASAN=OFF \
                -DSHORTEN_POR_CORPUS_FOR_SVMLEARN=ON \
                -DCMAKE_BUILD_TYPE:STRING=Release \
                -DWITH_GUI=ON \
                -DCTEST_OUTPUT_ON_FAILURE="ON" \
                ..
            ninja
            ninja install


