PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?item ?itemLabel
WHERE
{
    ?item wdt:P279* wd:Q17334923;
          rdfs:label ?itemLabel;
    FILTER (lang(?itemLabel) = "en")
}
