// Copyright 2004-2021 CEA LIST
// SPDX-FileCopyrightText: 2022 CEA LIST <gael.de-chalendar@cea.fr>
//
// SPDX-License-Identifier: MIT

#ifndef LIMA_CORELINGUISTICPROCESSINGCLIENTEXPORT_H
#define LIMA_CORELINGUISTICPROCESSINGCLIENTEXPORT_H

#include <common/LimaCommon.h>

#ifdef WIN32

#ifdef LIMA_CORELINGUISTICPROCESSINGCLIENT_EXPORTING
   #define LIMA_CORELINGUISTICPROCESSINGCLIENT_EXPORT    __declspec(dllexport)
#else
   #define LIMA_CORELINGUISTICPROCESSINGCLIENT_EXPORT    __declspec(dllimport)
#endif


#else // Not WIN32

#define LIMA_CORELINGUISTICPROCESSINGCLIENT_EXPORT

#endif

#endif
