ARG PYTHON_VERSION=3.8
ARG QT_VERSION=5.15.3
ARG LLVM_VERSION=14.0.6
FROM aymara/manylinux_2_24_with_qt${QT_VERSION}-python${PYTHON_VERSION}:latest as aymara_manylinux_2_24_with_qt
FROM aymara/manylinux_2_24_with_llvm${LLVM_VERSION}:latest as aymara_manylinux_2_24_with_llvm

FROM quay.io/pypa/manylinux_2_24_x86_64

ARG GCC_VERSION=10.1.0
ARG QT_VERSION=5.15
ARG QT_VERSION_MAJOR=5
ARG QT_FULL_VERSION=5.15.2
ARG PYTHON_VERSION="3.8"
ARG PYTHON_SHORT_VERSION="cp38-cp38"
# For python 3.7, it is 3.7.13
# For python 3.8, it is 3.8.13
ARG PYTHON_FULL_VERSION="3.8.13"

COPY --from=aymara_manylinux_2_24_with_qt /opt/qt${QT_VERSION_MAJOR} /opt/qt${QT_VERSION_MAJOR}
# COPY --from=aymara_manylinux_2_24_with_qt /opt/gcc-${GCC_VERSION} /opt/gcc-${GCC_VERSION}
COPY --from=aymara_manylinux_2_24_with_llvm /opt/llvm /opt/llvm

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/opt/python/${PYTHON_SHORT_VERSION}/bin:${PATH}"

RUN apt-get clean && apt-get update && apt-get install -y locales
RUN echo "LC_ALL=en_US.UTF-8" > /etc/default/locale && echo "LANG=en_US.UTF-8" >> /etc/default/locale && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && cp  /etc/default/locale /etc/environment && locale-gen en_US.UTF-8 && dpkg-reconfigure locales
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
RUN locale


RUN apt remove -y libpython3.5-stdlib libpython3.5-minimal
RUN apt-get update -y -qq && apt-get install -y -qq libpulse-mainloop-glib0 wget tar xz-utils libicu-dev


ENV PATH=/opt/qt${QT_VERSION_MAJOR}/bin:/opt/_internal/cpython-${PYTHON_FULL_VERSION}/bin:/opt/llvm/bin:/opt/qt${QT_VERSION_MAJOR}/${QT_FULL_VERSION}/gcc_64/bin:$PATH \
    LD_LIBRARY_PATH=/opt/qt${QT_VERSION_MAJOR}/lib:/opt/llvm/lib:$LD_LIBRARY_PATH \
    LLVM_INSTALL_DIR=/opt/llvm \
    CLANG_INSTALL_DIR=/opt/llvm \
    QTDIR=/opt/qt${QT_VERSION_MAJOR}
# ENV PATH=/opt/llvm/bin:/opt/gcc-${GCC_VERSION}/bin:/opt/qt${QT_VERSION_MAJOR}/${QT_FULL_VERSION}/gcc_64/bin:$PATH \
#     LD_LIBRARY_PATH=/opt/llvm/lib:/opt/gcc-${GCC_VERSION}/lib:/opt/gcc-${GCC_VERSION}/lib64:$LD_LIBRARY_PATH \
#     MANPATH=/opt/gcc-${GCC_VERSION}/share/man:$MANPATH \
#     INFOPATH=/opt/gcc-${GCC_VERSION}/share/info:$INFOPATH \
#     LLVM_INSTALL_DIR=/opt/llvm CLANG_INSTALL_DIR=/opt/llvm


# ENV CC=/opt/gcc-${GCC_VERSION}/bin/gcc CXX=/opt/gcc-${GCC_VERSION}/bin/g++

RUN python${PYTHON_VERSION} -m pip install scikit-build

# Install PySide${QT_VERSION_MAJOR} and shiboken${QT_VERSION_MAJOR} from source as binary installs are broken
# Done in /home/gael/Logiciels/
WORKDIR /
RUN echo "Downloading https://download.qt.io/official_releases/QtForPython/pyside${QT_VERSION_MAJOR}/PySide${QT_VERSION_MAJOR}-${QT_FULL_VERSION}-src/pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz" && wget -q https://download.qt.io/official_releases/QtForPython/pyside${QT_VERSION_MAJOR}/PySide${QT_VERSION_MAJOR}-${QT_FULL_VERSION}-src/pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz && tar xf pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz && mv /pyside-setup-opensource-src-${QT_FULL_VERSION} /pyside-setup && rm pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz
WORKDIR /pyside-setup
RUN install -d /opt/_internal/cpython-${PYTHON_FULL_VERSION}/lib/x86_64-linux-gnu/ && touch /opt/_internal/cpython-${PYTHON_FULL_VERSION}/lib/x86_64-linux-gnu/libpython${PYTHON_VERSION}.a && touch /opt/_internal/cpython-${PYTHON_FULL_VERSION}/lib/x86_64-linux-gnu/libpython${PYTHON_VERSION}m.a

WORKDIR /pyside-setup
RUN python${PYTHON_VERSION} -m pip install cmake


# RUN python${PYTHON_VERSION} setup.py install --cmake=/opt/python/cp${PYTHON_SHORT_VERSION}-cp${PYTHON_SHORT_VERSION}/bin/cmake --build-type=all
RUN python${PYTHON_VERSION} setup.py install --cmake=/opt/_internal/cpython-${PYTHON_FULL_VERSION}/bin/cmake --build-type=all --standalone --limited-api=yes

WORKDIR /
