ARG GCC_VERSION=10.1.0
FROM aymara/manylinux_2_24_with_gcc${GCC_VERSION}:latest
# ARG LLVM_VERSION="14.0.6"
# FROM aymara/manylinux_2_24_with_llvm${LLVM_VERSION}:latest

ARG GCC_VERSION=10.1.0
# ARG LLVM_VERSION="14.0.6"
ARG QT_VERSION="5.15"
ARG QT_VERSION_MAJOR="5"
ARG QT_VERSION_MINOR="15"
ARG QT_VERSION_PATCH="2"
ARG QT_FULL_VERSION="5.15.2"
ARG PYTHON_VERSION="3.8"
ARG PYTHON_SHORT_VERSION="cp38-cp38"
# For python 3.7, it is 3.7.13
# For python 3.8, it is 3.8.13
ARG PYTHON_FULL_VERSION="3.8.13"
ENV PATH="/opt/python/${PYTHON_SHORT_VERSION}/bin:${PATH}"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean && apt-get update && apt-get install -y locales
RUN echo "LC_ALL=en_US.UTF-8" > /etc/default/locale
RUN echo "LANG=en_US.UTF-8" >> /etc/default/locale
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN cp  /etc/default/locale /etc/environment
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
RUN locale-gen
RUN dpkg-reconfigure locales
RUN locale


RUN apt-get update && \
    apt-get install -y \
        wget build-essential pkg-config automake  gawk gettext \
        firebird-dev \
        freetds-dev \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-x \
        libasound2-dev \
        libavcodec-dev \
        libavformat-dev \
        libavutil-dev \
        libbz2-dev \
        libcap-dev \
        libdbus-1-dev \
        libdbus-glib-1-dev \
        libdrm-dev \
        libegl1-mesa-dev \
        libevent-dev \
        libfontconfig1-dev \
        libfreetype6-dev \
        libgbm-dev \
        libgcrypt20-dev \
        libgles2-mesa-dev \
        libglib2.0-dev \
        libgst-dev \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer1.0-dev \
        libicu-dev \
        libinput-dev \
        libiodbc2-dev \
        libjpeg62-turbo-dev \
        libjsoncpp-dev \
        libminizip-dev \
        libnss3-dev \
        libopus-dev \
        libpci-dev \
        libpng-dev \
        libpng16-16 \
        libpq-dev \
        libpulse-dev \
        librsvg2-common \
        libsnappy-dev \
        libsqlite0-dev \
        libsqlite3-dev \
        libsrtp0-dev \
        libsrtp2-dev \
        libssl-dev \
        libssl1.1 \
        libswscale-dev \
        libsystemd-dev \
        libudev-dev \
        libvpx-dev \
        libwayland-dev \
        libwebp-dev \
        libx11-dev \
        libx11-xcb-dev \
        libx11-xcb1 \
        libxcb-glx0-dev \
        libxcb-icccm4 \
        libxcb-icccm4-dev \
        libxcb-image0 \
        libxcb-image0-dev \
        libxcb-keysyms1 \
        libxcb-keysyms1-dev \
        libxcb-randr0-dev \
        libxcb-render-util0 \
        libxcb-render-util0-dev \
        libxcb-shape0-dev \
        libxcb-shm0 \
        libxcb-shm0-dev \
        libxcb-sync-dev \
        libxcb-sync1 \
        libxcb-xfixes0-dev \
        libxcb-xinerama0 \
        libxcb-xinerama0-dev \
        libxcb1 \
        libxcb1-dev \
        libxext-dev \
        libxi-dev \
        libxkbcommon-dev \
        libxrender-dev \
        libxslt1-dev \
        libxss-dev \
        libxtst-dev \
        ninja-build \
        nodejs \
        ruby \
        va-driver-all \
        lsb-release \
        libssl-dev \
        gperf \
        dos2unix

RUN apt remove -y libpython3.5-stdlib libpython3.5-minimal
RUN install -d /src
WORKDIR /src
RUN wget -q https://download.qt.io/archive/qt/${QT_VERSION}/${QT_FULL_VERSION}/single/qt-everywhere-src-${QT_FULL_VERSION}.tar.xz
RUN tar xf qt-everywhere-src-${QT_FULL_VERSION}.tar.xz

WORKDIR /

ENV BUILD_TARGET=/build
ENV SRC=/src

RUN mkdir -p "$BUILD_TARGET"

ENV PATH=/opt/gcc-${GCC_VERSION}/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/gcc-${GCC_VERSION}/lib:/opt/gcc-${GCC_VERSION}/lib64:$LD_LIBRARY_PATH
ENV MANPATH=/opt/gcc-${GCC_VERSION}/share/man:$MANPATH
ENV INFOPATH=/opt/gcc-${GCC_VERSION}/share/info:$INFOPATH

ENV CC=/opt/gcc-${GCC_VERSION}/bin/gcc
ENV CXX=/opt/gcc-${GCC_VERSION}/bin/g++
# ENV CC=/opt/llvm/bin/clang
# ENV CXX=/opt/llvm/bin/clang++
# ENV LLVM_USE_LINKER=lld
# ENV CPLUS_INCLUDE_PATH=/opt/llvm/include/c++/v1
# ENV C_INCLUDE_PATH=/opt/llvm/include/clang
# ENV LIBRARY_PATH=/opt/llvm/lib
# ENV LLVM_INSTALL_DIR=/opt/llvm
# ENV PATH=/opt/llvm/bin:$PATH
# ENV LD_LIBRARY_PATH=/opt/llvm/lib:$LD_LIBRARY_PATH

RUN echo "Building QT version $QT_FULL_VERSION."

# This build process is inspired by
# https://www.tal.org/tutorials/building-qt-512-raspberry-pi
ENV SRC_DIR="/src/qt-everywhere-src-${QT_FULL_VERSION}"

WORKDIR $BUILD_TARGET
RUN bash "${SRC_DIR}"/configure \
    -c++std c++17 \
    -confirm-license \
    -opensource \
    -dbus-linked \
    -no-eglfs \
    -no-evdev \
    -no-glib \
    -make libs \
    -no-cups \
    -no-gbm \
    -no-gtk \
    -no-pch \
    -no-xcb \
    -no-xcb-xlib \
    -nomake examples \
    -nomake tests \
    -prefix /opt/qt${QT_VERSION_MAJOR} \
    -qpa eglfs \
    -qt-pcre \
    -reduce-exports \
    -release \
    -skip qt3d \
    -skip qtactiveqt \
    -skip qtandroidextras \
    -skip qtcanvas3d \
    -skip qtcharts \
    -skip qtdatavis3d \
    -skip qtgamepad \
    -skip qtgraphicaleffects \
    -skip qtlocation \
    -skip qtlottie \
    -skip qtmacextras \
    -skip qtpurchasing \
    -skip qtquick3d \
    -skip qtquickcontrols \
    -skip qtquickcontrols2 \
    -skip qtquicktimeline \
    -skip qtscript \
    -skip qtscxml \
    -skip qtsensors \
    -skip qtserialbus \
    -skip qtserialport \
    -skip qtspeech \
    -skip qttools \
    -skip qtdoc \
    -skip qttranslations \
    -skip qtvirtualkeyboard \
    -skip qtwayland \
    -skip qtwebview \
    -skip qtwebengine \
    -skip qtwinextras \
    -skip qtx11extras \
    -skip wayland \
    -no-ssl \
    -system-freetype \
    -system-libjpeg \
    -system-libpng \
    -system-zlib

RUN make -j $(nproc) && make install
# RUN cmake --build . --parallel && cmake --install .

