FROM quay.io/pypa/manylinux_2_24_x86_64

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean && apt-get update && apt-get install -y locales
RUN echo "LC_ALL=en_US.UTF-8" > /etc/default/locale
RUN echo "LANG=en_US.UTF-8" >> /etc/default/locale
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN cp  /etc/default/locale /etc/environment
RUN locale-gen
RUN dpkg-reconfigure locales
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ARG BRANCH=master
ARG USE_TENSORFLOW="true"
ARG GITHUB_TOKEN
ARG LIMA_DISABLE_FSW_TESTING
ARG LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS
ARG NLTK_PTB_DP_FILE

RUN apt-get update -y -qq && apt-get install -y git build-essential pkg-config automake wget


RUN python3.8 -m pip install cmake ninja
ENV PATH="/opt/python/cp38-cp38/bin:${PATH}"

WORKDIR /
RUN wget -q https://launchpad.net/~limapublisher/+archive/ubuntu/ppa/+sourcefiles/tensorflow-for-lima/1.9-ubuntu7~20.10/tensorflow-for-lima_1.9.orig.tar.xz
RUN tar xf tensorflow-for-lima_1.9.orig.tar.xz
RUN git clone -b r1.9 https://github.com/aymara/tensorflow.git
RUN cp -r /tensorflow-for-lima-1.9/external /tensorflow
WORKDIR /tensorflow
#RUN bash ./download_dependencies.sh
RUN install -d /tensorflow/tensorflow-build
WORKDIR /tensorflow/tensorflow-build
RUN cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX=/tensorflow_for_lima ../tensorflow/contrib/cmake
RUN make -v -C /tensorflow/tensorflow-build -j 1
RUN make -C /tensorflow/tensorflow-build install


