FROM quay.io/pypa/manylinux_2_28_x86_64

ARG GCC_VERSION=10.1.0
ARG QT_VERSION=5.15
ARG QT_VERSION_MAJOR=5
ARG QT_FULL_VERSION=5.15.2
ARG PYSIDE_VERSION=2
ARG PYTHON_VERSION="3.8"
ARG PYTHON_SHORT_VERSION="cp38-cp38"
ARG PYTHON_FULL_VERSION="3.8.13"

ENV PATH="/opt/python/${PYTHON_SHORT_VERSION}/bin:${PATH}"

RUN yum install -y wget gcc-toolset-10.x86_64 ninja-build libicu-devel.x86_64  "qt5-*.x86_64" qt5-devel.noarch \
    clang.x86_64 python3-clang.x86_64 llvm-devel.x86_64 clang-devel.x86_64 libxml2-devel.x86_64 libxslt-devel.x86_64 \
    python3-sphinx.noarch
RUN ln -s /usr/bin/uic-qt5 /usr/bin/uic && \
    ln -s /usr/bin/rcc-qt5 /usr/bin/rcc && \
    ln -s /usr/lib64/libclang.so.13 /usr/lib64/libclang.so.1
ENV CC=/opt/rh/gcc-toolset-10/root/usr/bin/gcc \
    CXX=/opt/rh/gcc-toolset-10/root/usr/bin/g++

RUN python${PYTHON_VERSION} -m pip install scikit-build

# Install PySide${QT_VERSION_MAJOR} and shiboken${QT_VERSION_MAJOR} from source as binary installs are broken
# Done in /home/gael/Logiciels/
WORKDIR /
RUN echo "Downloading https://download.qt.io/official_releases/QtForPython/pyside${PYSIDE_VERSION}/PySide${PYSIDE_VERSION}-${QT_FULL_VERSION}-src/pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz" && wget -q https://download.qt.io/official_releases/QtForPython/pyside${PYSIDE_VERSION}/PySide${PYSIDE_VERSION}-${QT_FULL_VERSION}-src/pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz && tar xf pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz && mv /pyside-setup-opensource-src-${QT_FULL_VERSION} /pyside-setup && rm pyside-setup-opensource-src-${QT_FULL_VERSION}.tar.xz
WORKDIR /pyside-setup
RUN install -d /opt/_internal/cpython-${PYTHON_FULL_VERSION}/lib/x86_64-linux-gnu/ && touch /opt/_internal/cpython-${PYTHON_FULL_VERSION}/lib/x86_64-linux-gnu/libpython${PYTHON_VERSION}.a && touch /opt/_internal/cpython-${PYTHON_FULL_VERSION}/lib/x86_64-linux-gnu/libpython${PYTHON_VERSION}m.a

WORKDIR /pyside-setup
RUN python${PYTHON_VERSION} setup.py install --build-type=all --limited-api=yes
WORKDIR /
RUN rm -Rf /pyside-setup

