FROM manjarolinux/base:latest

RUN pacman -Syu
RUN pacman -Sy --noconfirm --needed base-devel git cmake clang ninja qt5 boost qwt enchant tre
RUN pacman -Sy --noconfirm --needed python-nltk
# RUN pacman -Sy --noconfirm --needed qhttpserver

ARG BRANCH=master
ARG USE_TENSORFLOW="true"
ARG GITHUB_TOKEN
ARG LIMA_DISABLE_FSW_TESTING
ARG LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS
ARG NLTK_PTB_DP_FILE

# # Setup
# RUN apt-get update -y -qq && apt-get install -y apt-utils lsb-release git gcc g++ make curl python3-nltk gawk wget python3 ninja-build qtbase5-dev-tools libqt5xmlpatterns5-dev libqt5qml5 qtdeclarative5-dev qml-module-qtquick-extras qml-module-qtquick-controls qml-module-qtquick-layouts qml-module-qtquick2 libenchant-2-dev libtre-dev libboost-all-dev gnupg build-essential libssl-dev nodejs npm
#
# RUN wget https://launchpad.net/~limapublisher/+archive/ubuntu/ppa/+files/libtensorflow-for-lima-generic_1.9-ubuntu7~20.04_amd64.deb -q \
#     && dpkg -i libtensorflow-for-lima-generic_1.9-ubuntu7~20.04_amd64.deb \
#     && rm -f libtensorflow-for-lima-generic_1.9-ubuntu7~20.04_amd64.deb
#
# RUN wget https://launchpad.net/~limapublisher/+archive/ubuntu/ppa/+files/libtensorflow-for-lima-dev_1.9-ubuntu7~20.04_amd64.deb -q \
#     && dpkg -i libtensorflow-for-lima-dev_1.9-ubuntu7~20.04_amd64.deb \
#     && rm -f libtensorflow-for-lima-dev_1.9-ubuntu7~20.04_amd64.deb

# # Install recent cmake
# WORKDIR /cmake_build
# RUN wget --no-check-certificate https://cmake.org/files/v3.16/cmake-3.16.4-Linux-x86_64.sh -q
# RUN sh cmake-3.16.4-Linux-x86_64.sh --prefix=/usr --exclude-subdir --skip-license
# RUN cmake --version
# WORKDIR /

# RUN npm install -g json

RUN sed -ie "s|DEFAULT_URL = 'http://nltk.googlecode.com/svn/trunk/nltk_data/index.xml'|DEFAULT_URL = 'http://nltk.github.com/nltk_data/'|" /usr/lib/python*/*/nltk/downloader.py
RUN python3 -m nltk.downloader -d nltk_data dependency_treebank
RUN cat nltk_data/corpora/dependency_treebank/wsj_*.dp | grep -v "^$" > nltk_data/corpora/dependency_treebank/nltk-ptb.dp

WORKDIR /
RUN pacman -Sy --noconfirm --needed dos2unix wget go
RUN git clone https://aur.archlinux.org/yay-git.git
WORKDIR /yay-git
RUN useradd -ms /bin/bash  yay
RUN echo "yay ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN chown -R yay /yay-git
USER yay
RUN yes | makepkg -si
RUN yes | yay -S debtap
USER root
WORKDIR /

COPY continuous_integration/svmtool.sh  continuous_integration/svmtool-cpp.sh continuous_integration/qhttpserver.sh /
RUN /svmtool.sh $GITHUB_TOKEN
# RUN /svmtool-cpp.sh $GITHUB_TOKEN
# RUN /qhttpserver.sh $GITHUB_TOKEN
RUN install -d /svmtool-cpp
RUN SVMTOOL_LATEST_RELEASE_JSON=$(curl -s https://api.github.com/repos/aymara/svmtool-cpp/releases/latest?access_token=$GITHUB_TOKEN) && echo "SVMTOOL_LATEST_RELEASE_JSON=$SVMTOOL_LATEST_RELEASE_JSON" && URL=$(echo "$SVMTOOL_LATEST_RELEASE_JSON" | grep browser_download_url | grep debian9 | grep '.deb"' | head -n 1 | cut -d '"' -f 4) && echo "URL=$URL" && curl  -vLJ -H 'Accept: application/octet-stream' $URL?access_token=$GITHUB_TOKEN -o /svmtool-cpp/svmtool.deb
WORKDIR /svmtool-cpp
RUN debtap -u
RUN debtap -Q svmtool.deb
RUN ls /svmtool-cpp
RUN ls /svmtool-cpp
RUN sudo pacman --noconfirm -U ./*.zst

RUN mkdir -p /src/
RUN git clone --branch=$BRANCH --recurse-submodules https://${GITHUB_TOKEN}@github.com/aymara/lima /src/lima
RUN ls /src
RUN ls /src/lima/extern/fastText
RUN ls /src/lima/extern/fastText/src
WORKDIR /src/lima
RUN mkdir -p /src/lima/build
WORKDIR /src/lima/build

#ENV PERL5LIB /SVMTool-1.3.1/lib:$PERL5LIB
#ENV PATH /SVMTool-1.3.1/bin:/usr/share/apps/lima/scripts:/usr/bin:$PATH
ENV NLTK_PTB_DP_FILE /nltk_data/corpora/dependency_treebank/nltk-ptb.dp
ENV LIMA_DISABLE_FSW_TESTING true
ENV LIMA_DISABLE_CPACK_DEBIAN_PACKAGE_SHLIBDEPS true
ENV LIMA_DIST /usr
ENV LIMA_CONF /usr/share/config/lima
ENV LIMA_RESOURCES /usr/share/apps/lima/resources

# Build
#
RUN cmake -G Ninja -DLIMA_RESOURCES:STRING=build -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE:STRING=Release -DLIMA_VERSION_RELEASE:STRING="$(cat /src/lima/release)" -DSHORTEN_POR_CORPUS_FOR_SVMLEARN:BOOL=ON -DWITH_DEBUG_MESSAGES=ON -DWITH_ARCH=OFF -DWITH_ASAN=OFF -DWITH_GUI=ON ..
RUN ninja
RUN ninja test
RUN ninja install
# RUN ninja package
# RUN install -D -t /usr/share/apps/lima/packages /src/lima/build/*.deb
#
# WORKDIR /usr/share/apps/lima/tests
# RUN /bin/bash -c "set -o pipefail && tva --language=eng test-eng.*.xml 2>&1 | tee tva-eng.log"
# RUN /bin/bash -c "set -o pipefail && tva --language=fre test-fre.default.xml test-fre.disambiguated.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.sa.xml test-fre.se.xml test-fre.simpleword.xml test-fre.tokenizer.xml 2>&1 | tee tva-fre.log"
# WORKDIR /usr/share/apps/lima/tests/xmlreader
# RUN /bin/bash -c "set -o pipefail && tvx --language=eng --language=fre test-fre.xmlreader.xml 2>&1 | tee tvx-fre.log"
#
# # # install github-release to be able to deploy packages
# # RUN wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 -q && tar xjf linux-amd64-github-release.tar.bz2 && cp bin/linux/amd64/github-release /usr/bin
# #
# # # install python packages necessary to use the language resources install script
# # RUN apt-get install -y python3-pip -qq
# # RUN /bin/bash -c "if [ \"$USE_TENSORFLOW\" = true ] ; then pip3 install arpy requests tqdm ; fi"
# #
# # # install English and French UD models
# # RUN /bin/bash -c "if [ \"$USE_TENSORFLOW\" = true ] ; then lima_models.py -l english ; fi"
# # RUN /bin/bash -c "if [ \"$USE_TENSORFLOW\" = true ] ; then lima_models.py -l french ; fi"
# #
