#! /usr/bin/perl -s

open(SOURCE,"$ARGV[0]");
open(CIBLE,">$ARGV[1]");

$ligne = <SOURCE>;
while ($ligne ne "") 
{
			if ($ligne =~ /^\#/) 
			{
				$ligne = <SOURCE>;
				next;
			}
      chop($ligne);
      print CIBLE ("$ligne\t\t\n");
      $ligne = <SOURCE>;
}
