#!/bin/bash

CHARCHART=$1
PROPERTY_CODE=$2
SYMBOLIC_CODE=$3
DICTIONARY_INPUT=$4

export LC_ALL="C"

compile-dictionary --charChart=$CHARCHART --extractKeyList=keys $DICTIONARY_INPUT
sort -T . -u keys > keys.sorted
testDict16 --charSize=2 --listOfWords=keys.sorted --output=$DICTIONARY_INPUT.key.dat > output
testDict16 --charSize=2 --input=$DICTIONARY_INPUT.key.dat --spare --output=$DICTIONARY_INPUT.key.dat >> output

compile-dictionary --charChart=$CHARCHART --fsaKey=$DICTIONARY_INPUT.key.dat --propertyFile=$PROPERTY_CODE --symbolicCodes=$SYMBOLIC_CODE --output=$DICTIONARY_INPUT.data.dat $DICTIONARY_INPUT


